version: "3"
services:
  registry:
    image: registry-service
    ports:
      - "8099"
    networks:
      - service-network
    depends_on:
      - config

  config:
    image: config-service
    ports:
      - "8081"
    networks:
      - service-network

networks:
  service-network:
