version: "3"
services:
  inventory-service:
    image: inventory-service
    ports:
      - "8091:8091"
    networks:
      - foodyeah-network
    depends_on:
      - registry-service
    restart: on-failure

  gateway-service:
    image: gateway-service
    ports:
      - "8080:8080"
    networks:
      - foodyeah-network
    depends_on:
      - user-service
      - inventory-service
      - food-service
    restart: on-failure

  user-service:
    image: user-service
    ports:
      - "8093:8093"
    networks:
      - foodyeah-network
    depends_on:
      - registry-service
    restart: on-failure

  food-service:
    image: food-service
    ports:
      - "8092:8092"
    networks:
      - foodyeah-network
    depends_on:
      - registry-service
    restart: on-failure

  registry-service:
    image: registry-service
    ports:
      - "8099:8099"
    networks:
      - foodyeah-network
    depends_on:
      - config-service
    restart: on-failure

  config-service:
    image: config-service
    ports:
      - "8081:8081"
    networks:
      - foodyeah-network

  admin-service:
    image: admin-service
    ports:
      - "8086:8086"
    networks:
      - foodyeah-network

networks:
  foodyeah-network:
