version: "3"
services:
  registry-service:
    image: registry-service
    ports:
      - "8099:8099"
    networks:
      - service-network
    depends_on:
      - config-service

  config-service:
    image: config-service
    ports:
      - "8081:8081"
    networks:
      - service-network

networks:
  service-network:
