spring:
  application:
    name: food-service
  cloud:
    config:
      uri: http://localhost:8081
      username: paulsoftcomp
      password: paulsoftcompany123
  boot:
    admin:
      client:
        url: http://localhost:8082

# Eureka Client
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8099/eureka/
