server:
  port: 8080

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8099/eureka/

spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: food-service
          uri: lb://food-service
          predicates:
            - Path=/foods/**
        - id: inventory-service
          uri: lb://inventory-service
          predicates:
            - Path=/products/**
            - Path=/product-categories/**
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/customers/**