server:
  port: 8080

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8099/eureka/

spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: food-service
          uri: lb://food-service
          predicates:
            - Path=/api/fs/**

        - id: inventory-service
          uri: lb://inventory-service
          predicates:
            - Path=/api/is/**

        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/api/us/**
#El predicate es la nueva ruta que toma , la ruta general, pero se respetan las rutas dentro del propio microservicio
#El uri es lb://id-del-servicio
