spring: 
  application: 
    name: user-service 
  cloud: 
    config: 
      uri: http://localhost:8081 
      username: name 
      password: password 
  boot: 
    admin: 
      client:
        url: http://localhost:8084
