# Server configuration
server:
  port: 8081 #set your port
# Spring Boot configuration
spring:
  # Database
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost/inventario-foodyeah
    username: postgres
    password: Kingjinx18
  # JPA properties
  jpa:
    database: postgresql
    hibernate:
      ddl-auto: update # When you launch the application for the first time - switch "none" at "create"
    show-sql: false
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        show_sql: true
        use_sql_comment: false
        format_sql: false

